name: nightly
"on":
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - run: pnpm i
      - run: pnpm build

      # canary
      - run: |
          pnpm -C packages/plugin-rsc i react-server-dom-webpack@canary
          pnpm i --no-frozen-lockfile
          pnpm -C packages/plugin-rsc build
          cp -rf packages/plugin-rsc packages/plugin-rsc-canary
          sed -i 's#"name": "@vitejs/plugin-rsc"#"name": "@vitejs/plugin-rsc-canary"#' packages/plugin-rsc-canary/package.json

      # experimental
      - run: |
          pnpm -C packages/plugin-rsc i react-server-dom-webpack@experimental
          pnpm i --no-frozen-lockfile
          pnpm -C packages/plugin-rsc build
          cp -rf packages/plugin-rsc packages/plugin-rsc-experimental
          sed -i 's#"name": "@vitejs/plugin-rsc"#"name": "@vitejs/plugin-rsc-experimental"#' packages/plugin-rsc-experimental/package.json

      - run: |
          pnpx pkg-pr-new publish --comment=off \
            packages/plugin-rsc-canary \
            packages/plugin-rsc-experimental \
